### ISSUE TITLE
post後のrefreshが正しく動作しない

### ISSUE THREAD

**Issue by dongri** [akanoren/redsky#9]
https://github.com/akanoren/redsky/blob/main/src/lib/client.ts#L97

ここでやるとrefreshされるかと思ったら、うまく動作しない

**Comment by minoritea** [comment]
https://github.com/akanoren/redsky/blob/d40882671522bb2b145ae86524e47fc47429af79/src/lib/client.ts#L92
ここにawait入れてください

**Comment by dongri** [comment]
なるほど！
